import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MyNavbar } from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased    `}
      >
        {/* <div className="rounded-2xl overflow-hidden  container mx-auto px-10 "></div> */}

        <div className="container mx-auto p-3">
          <div className="relative w-full ">
            {/* <div className="absolute inset-0 h-full w-full scale-[0.95] transform rounded-full bg-red-500 bg-gradient-to-r from-blue-500 to-teal-500 blur-3xl" /> */}
            <div className="relative  overflow-hidden rounded-2xl  px-4 ">
              <MyNavbar />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
